version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
      - 5555:5555
    env_file:
      - .env.local
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
    ports:
      - 8081:8081
    depends_on:
      - mongodb
